version: "3"
services:
  nginx:
    build:
      context: /Users/lipeng/png/nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    privileged: true
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    links:
      - "php72:php72"
      - "php56:php56"
    networks:
      - default

  php72:
    build:
      context: /Users/lipeng/png/php72/
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP72_VERSION}
        PHP_XDEBUG: ${PHP72_XDEBUG}
        PHP_SWOOLE: ${PHP72_SWOOLE}
        PHP_REDIS: ${PHP72_REDIS}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    expose:
      - "9000"
    ports:
      - 9001:9000
    container_name: php72
    privileged: true
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/:rw
      - ${PHP72_LOG_DIR}:/data/logs/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php56:
    build:
      context: /Users/lipeng/png/php56
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP56_VERSION}
        PHP_XDEBUG: ${PHP56_XDEBUG}
        PHP_SWOOLE: ${PHP56_SWOOLE}
        PHP_REDIS: ${PHP56_REDIS}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    expose:
      - "9000"
    ports:
      - 9002:9000
    container_name: php56
    privileged: true
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/:rw
      - ${PHP56_LOG_DIR}:/data/logs/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

        #  php54:
        #    build:
        #      context: .
        #      args:
        #        PHP_VERSION: ${PHP54_VERSION}
        #        PHP_XDEBUG: ${PHP54_XDEBUG}
        #        PHP_SWOOLE: ${PHP54_SWOOLE}
        #        PHP_REDIS: ${PHP54_REDIS}
        #        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
        #    volumes:
        #      - ${SOURCE_DIR}:/var/www/html/:rw
        #      - ${PHP54_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
        #      - ${PHP54_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
        #    restart: always
        #    cap_add:
        #      - SYS_PTRACE
        #    networks:
        #      - default
        #
  # mysql:
  #   image: mysql:${MYSQL_VERSION}
  #   ports:
  #     - "${MYSQL_HOST_PORT}:3306"
  #   volumes:
  #     - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/:rw
  #     - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
  #   restart: always
  #   privileged: true
  #   networks:
  #     - default
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  # redis:
  #   image: redis:${REDIS_VERSION}
  #   ports:
  #     - "${REDIS_HOST_PORT}:6379"
  #   volumes:
  #     - ${REDIS_CONF_FILE}:/etc/:rw
  #   restart: always
  #   privileged: true
  #   entrypoint: ["redis-server", "/etc/redis.conf"]
  #   networks:
  #     - default
    

        #  phpmyadmin:
        #    image: phpmyadmin/phpmyadmin:latest
        #    ports:
        #      - "${PHPMYADMIN_HOST_PORT}:80"
        #    networks:
        #      - default
        #    environment:
        #      - PMA_HOST=mysql
        #      - PMA_PORT=3306
        #
        #  phpredisadmin:
        #    image: erikdubbelboer/phpredisadmin:latest
        #    ports:
        #      - "${REDISMYADMIN_HOST_PORT}:80"
        #    networks:
        #      - default
        #    environment:
        #      - REDIS_1_HOST=redis
        #      - REDIS_1_PORT=6379

networks:
  default:
